/*! \file	mdtype.cpp
 *	\brief	Implementation of classes that define metadata type info
 *
 *			Class MDDict holds the overall dictionary definitions and
 *          manages loading them from a dictionary file and adding new
 *			metadata types.
 *<br><br>
 *			Class MDType holds info about a specific metadata type
 *<br><br>
 *			These classes are currently wrappers around KLVLib structures
 */

#include "mdtype.h"

//! MDDict constructor
/*! Loads the dictionary from the specified file
*/
mxflib::MDDict::MDDict(const char *DictFile)
{
	MainDict = LoadDictionary(DictFile);
}


//! MDDict destructor
/*! Frees all items loaded and generated by this object
*/
mxflib::MDDict::~MDDict()
{
	// Free the main dictionary (as long as it has been loaded)
	if (MainDict) FreeDictionary(MainDict);
}




