	// Types definitions converted from file types.xml
	MXFLIB_TYPE_START(dict_types)
		MXFLIB_TYPE_BASIC("Float32", "32 bit IEEE Floating Point", 4, false)
		MXFLIB_TYPE_BASIC("Float64", "64 bit IEEE Floating Point", 8, false)
		MXFLIB_TYPE_BASIC("Float80", "80 bit IEEE Floating Point", 10, false)
		MXFLIB_TYPE_BASIC("Int8", "8 bit integer", 1, false)
		MXFLIB_TYPE_BASIC("Int16", "16 bit integer", 2, true)
		MXFLIB_TYPE_BASIC("Int24", "24 bit integer", 3, true)
		MXFLIB_TYPE_BASIC("Int32", "32 bit integer", 4, true)
		MXFLIB_TYPE_BASIC("Int64", "64 bit integer", 8, true)
		MXFLIB_TYPE_BASIC("Uint8", "8 bit unsigned integer", 1, false)
		MXFLIB_TYPE_BASIC("Uint16", "16 bit unsigned integer", 2, true)
		MXFLIB_TYPE_BASIC("Uint24", "24 bit unsigned integer", 3, true)
		MXFLIB_TYPE_BASIC("Uint32", "32 bit unsigned integer", 4, true)
		MXFLIB_TYPE_BASIC("Uint64", "64 bit unsigned integer", 8, true)
		MXFLIB_TYPE_INTERPRETATION("VersionType", "Version number (created from major*256 + minor)", "Uint16", 0)
		MXFLIB_TYPE_INTERPRETATION("UTF16", "Unicode UTF-16 coded character", "Uint16", 0)
		MXFLIB_TYPE_INTERPRETATION("Boolean", "Boolean", "Uint8", 0)
		MXFLIB_TYPE_INTERPRETATION("ISO7", "ISO 7-Bit Coded Character", "Uint8", 0)
		MXFLIB_TYPE_INTERPRETATION("Length", "Length in Edit Units", "Int64", 0)
		MXFLIB_TYPE_INTERPRETATION("Position", "Position measured in Edit Units", "Int64", 0)
		MXFLIB_TYPE_INTERPRETATION("RGBACode", "Enumerated value specifying component in an RGBALayoutItem", "Uint8", 0)
		MXFLIB_TYPE_MULTIPLE("UTF16String", "Unicode UTF-16 coded string", "UTF16", false, 0)
		MXFLIB_TYPE_MULTIPLE("Int32Array", "Array of Int32", "Int32", false, 0)
		MXFLIB_TYPE_MULTIPLE("Uint32Array", "Array of Uint32", "Uint32", false, 0)
		MXFLIB_TYPE_MULTIPLE("Int64Array", "Array of Int64", "Int64", false, 0)
		MXFLIB_TYPE_MULTIPLE("Uint8Array", "Array of Uint8", "Uint8", false, 0)
		MXFLIB_TYPE_MULTIPLE("ISO7String", "ISO 7-Bit coded string", "ISO7", false, 0)
		MXFLIB_TYPE_MULTIPLE("Int32Batch", "Batch of Int32 values", "Int32", true, 0)
		MXFLIB_TYPE_MULTIPLE("Uint32Batch", "Batch of Uint32 values", "Uint32", true, 0)
		MXFLIB_TYPE_BASIC("RAW", "Raw data bytes, unknown representation", 0, false)
		MXFLIB_TYPE_INTERPRETATION("Stream", "Data mapped to AAF Stream, MXF represents using a SID", "RAW", 0)
		MXFLIB_TYPE_INTERPRETATION("DataValue", "Data represented as AAF varying array of UInt8", "Uint8Array", 0)
		MXFLIB_TYPE_INTERPRETATION("Identifier", "Generic Identifier", "Uint8Array", 0)
		MXFLIB_TYPE_INTERPRETATION("Opaque", "Opaque Data", "Uint8Array", 0)
		MXFLIB_TYPE_INTERPRETATION("UMID", "SMPTE UMID", "Identifier", 32)
		MXFLIB_TYPE_INTERPRETATION("UID", "UID", "Identifier", 0)
		MXFLIB_TYPE_INTERPRETATION("Label", "SMPTE Universal Label", "Identifier", 16)
		MXFLIB_TYPE_INTERPRETATION("UUID", "UUID", "Identifier", 16)
		MXFLIB_TYPE_INTERPRETATION("AUID", "AUID is a Label or a swapped UUID", "Label", 0)
		MXFLIB_TYPE_INTERPRETATION("PackageID", "Package ID", "UMID", 0)
		MXFLIB_TYPE_INTERPRETATION("StrongRef", "Strong Reference", "UUID", 0)
		MXFLIB_TYPE_INTERPRETATION("WeakRef", "Weak Reference", "UUID", 0)
		MXFLIB_TYPE_MULTIPLE("AUIDArray", "Array of AUIDs", "AUID", false, 0)
		MXFLIB_TYPE_MULTIPLE("LabelBatch", "Batch of SMPTE Universal Labels", "Label", true, 0)
		MXFLIB_TYPE_MULTIPLE("StrongRefArray", "Array of StrongRefs", "StrongRef", false, 0)
		MXFLIB_TYPE_MULTIPLE("StrongRefBatch", "Batch of StrongRefs", "StrongRef", true, 0)
		MXFLIB_TYPE_MULTIPLE("WeakRefArray", "Array of WeakRefs", "StrongRef", false, 0)
		MXFLIB_TYPE_MULTIPLE("WeakRefBatch", "Batch of WeakRefs", "WeakRef", true, 0)
		MXFLIB_TYPE_COMPOUND("Rational", "Rational")
			MXFLIB_TYPE_COMPOUND_ITEM("Numerator", "Numerator", "Int32", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Denominator", "Denominator", "Int32", 0)
		MXFLIB_TYPE_COMPOUND_END
		MXFLIB_TYPE_COMPOUND("Timestamp", "Date and Time")
			MXFLIB_TYPE_COMPOUND_ITEM("Year", "Year", "Uint16", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Month", "Month", "Uint8", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Day", "Day", "Uint8", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Hours", "Hours", "Uint8", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Minutes", "Minutes", "Uint8", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Seconds", "Seconds", "Uint8", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("msBy4", "msBy4", "Uint8", 0)
		MXFLIB_TYPE_COMPOUND_END
		MXFLIB_TYPE_COMPOUND("ProductVersion", "Product Version Number")
			MXFLIB_TYPE_COMPOUND_ITEM("Major", "Major", "Uint16", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Minor", "Minor", "Uint16", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Patch", "Patch", "Uint16", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Build", "Build", "Uint16", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Release", "Release", "Uint16", 0)
		MXFLIB_TYPE_COMPOUND_END
		MXFLIB_TYPE_COMPOUND("Indirect", "Indirect Data")
			MXFLIB_TYPE_COMPOUND_ITEM("Type", "Type of Data", "Label", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Data", "Data", "Uint8Array", 0)
		MXFLIB_TYPE_COMPOUND_END
		MXFLIB_TYPE_COMPOUND("RGBALayoutItem", "Item in an RGBALayout array")
			MXFLIB_TYPE_COMPOUND_ITEM("Code", "Enumerated value specifying component", "RGBACode", 0)
			MXFLIB_TYPE_COMPOUND_ITEM("Depth", "Number of bits occupied", "Uint8", 0)
		MXFLIB_TYPE_COMPOUND_END
		MXFLIB_TYPE_MULTIPLE("RationalArray", "Array of Rational", "Rational", false, 0)
		MXFLIB_TYPE_MULTIPLE("RGBALayout", "Specifies the type, order and size of the components within the pixel", "RGBALayoutItem", false, 8)
	MXFLIB_TYPE_END
